#!/usr/bin/env php
<?php
/**
 * Sample Player
 *
 * Provides samples of various simple Move makers
 *
 * @link https://github.com/stjohnjohnson/ScrabblerBot
 * @author St. John Johnson <st.john.johnson@gmail.com>
 */

namespace Scrabbler;

/** Scrabbler Player */
require_once 'src/player.php';

if ($argc < 1) {
    die('Usage: scrabbler.php [Wordlist.txt] [BotName]' . PHP_EOL);
}

ini_set('memory_limit', '4G');

$foo = new Player(array(
    'log' => Player::LOG_INFO,
    'lexicon' => $argv[1] ?? unserialize(file_get_contents('lists/slowa.tree')),
    'method' => $argv[2] ?? 'HighestScore',
    'lang' => 'PL'
));

$foo->simulate(new Player(array(
    'lexicon' => $foo->lexicon,
    'method' => 'HighestScore'
)));

//$foo->execute();
